logging.level.=DEBUG

sasl.oauthbearer.token.endpoint.url=https://login.microsoftonline.com/e6017ef7-e18e-41f2-a27f-6a5b1f9f7e1a/oauth2/token
sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerLoginCallbackHandler

bearer.auth.credentials.source=SASL_OAUTHBEARER_INHERIT
bearer.auth.logical.cluster=lsrc-m8wzjx